name: Issue Forms Body Parser

on: issues

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
      - run: |
         echo '${{ steps.parse.outputs.data }}' > issue.json
         cat issue.json 
        id: parse-json
      - run: node parse-json.js  
      - run: |
         echo  ${{ steps.parse-json.outputs }}
         echo '${{ steps.parse-json.outputs.data }}' > parsed-json.json 
         cat parsed-json.json          
